PlummersSoftwareLLC/NightDriverStrip

CONTRIBUTING.md, README.md, include/globals.h, include/ledbuffer.h, include/ledmatrixgfx.h, include/soundanalyzer.h, include/spiffswebserver.h, src/audio.cpp, src/effects.cpp, src/main.cpp, src/network.cpp, src/screen.cpp
Just fixing a few minor spelling errors here and there.
Thank you Dave (& other contributors) for making this project open source and available for the general public! This is truly a gift to the LED hacker community... much love.
=> Minor typo fixes

include/globals.h, include/socketserver.h, platformio.ini, src/drawing.cpp, src/main.cpp
Fix framerate and memory issues by going back to framework v3.5.0
=> Response packet

include/effects/strip/snakeeffect.h
An effect based on Snake.
Adding a new effect based on Snake.
Quick Demo on test strip: https://www.youtube.com/shorts/hj-S5HjzzgM
=> Created the Snake 1D Effect

buddybuild.sh, include/effects/matrix/PatternLife.h, include/network.h, include/remotecontrol.h, include/screen.h, include/soundanalyzer.h, platformio.ini, src/audio.cpp, src/network.cpp
Refactor char * to String, refactor audioanalyzer, clean up includes
=> Merge Dave's fork into PlummersSoftwareLLC

.github/workflows/CI.yml
This makes GitHub CI (Actions) build all configurations included in platformio.ini.
=> Build all environments/configs in CI

.github/workflows/CI.yml, README.md, include/deviceconfig.h, include/effectfactories.h, include/effects/matrix/PatternSubscribers.h, include/effects/matrix/PatternWeather.h, include/globals.h, include/ledstripeffect.h, include/network.h, include/taskmgr.h, include/types.h, include/webserver.h, src/deviceconfig.cpp, src/effects.cpp, src/effects/matrix/PatternSubscribers.cpp, src/jsonserializer.cpp, src/ledstripeffect.cpp, src/main.cpp, src/network.cpp, src/webserver.cpp
This PR includes a number of changes that reduce memory usage, specifically on devices that run many effects. For one, the Mesmerizer project in its current state leaves so little available RAM that the web server fails to start at boot.
Note that the ways to create and return effect setting specs, and for an effect to perform data fetches from the Internet change with the merge of this PR. For both, `PatternSubscribers` can (still) be used as a reference.
Furthermore, this PR includes a new version of the CI (GitHub Actions) script. It now uses the recommended installation script to install PlatformIO.
=> Save memory

include/effects/matrix/PatternMaze.h, include/effects/matrix/spectrumeffects.h, include/gfxbase.h, include/globals.h, include/screen.h, include/socketserver.h, include/soundanalyzer.h, include/taskmgr.h, platformio.ini, samples/videoserver/VideoServer2.py, samples/videoserver/videoserver.py, src/audio.cpp, src/drawing.cpp, src/effects.cpp, src/main.cpp, src/network.cpp, src/screen.cpp
Rollup of all the major checkins.  Tested on Mesmerizer, M5 Spectrum, Feather S3, Heltec V3.  104K Free, drawing and refresh nominal.
=> Merge davepl fork in main 

include/effects.h, include/effects/matrix/spectrumeffects.h, include/effects/strip/misceffects.h, include/gfxbase.h, include/globals.h, include/ledstripeffect.h, include/ledstripgfx.h, include/soundanalyzer.h, platformio.ini, src/audio.cpp, src/effects.cpp, src/main.cpp
Integrate all changes from the hexagon branch, including hex drawing and improved audio effects
=> Update main fork from davepl's hexagon work

.github/workflows/CI.yml
This is a small update to the naming used within the new parallelized CI workflow. As the changes are mainly cosmetic and already tested in my fork, I'll merge myself when CI completes.
=> Clarify new CI workflow naming

platformio.ini
Removes port specifications that I missed while reviewing #362.
=> Remove ports from platformio.ini

include/ledstripeffect.h, src/effects.cpp, src/jsonserializer.cpp, src/main.cpp, src/network.cpp, src/ntptimeclient.cpp, src/socketserver.cpp, src/webserver.cpp
Finally got CMakeList in good enough shape to let CLion at it. I think we're
running out of nits. :-)
I have enough blinkin in the bank to cover a loan on these bits.
=> Get the warnings that Dave missed yesterday

.github/workflows/CI.yml, include/ledstripeffect.h, src/main.cpp, src/network.cpp, src/ntptimeclient.cpp, src/socketserver.cpp, tools/bake_installer.py
This:
- Create more Actions runner disk space for the web installer build - recent builds have failed due to the runner running out of disk space
- Only builds those environments that are included in the installer when baking it
- Runs the "regular" CI workflow for the main branch as well, to ensure everything builds
- Fixes a number of format string specifier mismatches that generated warnings while testing the previous points
- Reverts the revert of three changes in main.cpp (fixed in #382, reverted in #386)
=> Fix and improve web installer build in CI, fix small bugs

.github/workflows/CI.yml, README.md
Make it easier for a first-time contributor to recognize that the best 'demo' for their hardware may not actually be named 'demo' .
=> Document various 'demo' builds

include/effectmanager.h
For additional analysis and discussion, see bugreport. #408 
Fixes https://github.com/PlummersSoftwareLLC/NightDriverStrip/issues/408
=> Let PreviousEffect() traverse the entire table when remote-ing

CODEBASE_INTRO.md, README.md
This adds an introduction to the NightDriverStrip codebase to the existing documentation set.  
Note that this does not aim to be the "be all and end all" regarding NightDriverStrip development documentation, but it does intend to give the reader a solid basis for further exploration and, possibly, eventually contributing to the project.
I'm at the stage where I'm still going to let this simmer for a few days before pushing forward towards merging. I'm opening the PR now to allow others to already read and review the introduction in its current state.
For purposes of completeness: the PR also makes some small changes to the main README.
=> Add introduction to codebase

site/package-lock.json, site/package.json, tools/bake_site.py
This fixes #464 and this fixes #447
=> Dependency update

src/main.cpp
=> Swap parameters when writing WiFi config

include/deviceconfig.h, site/src/components/home/config/configDialog.jsx
Fixes #504. Added descriptions for checkboxes, added padding before input names/titles. Increased font size of titles and made titles consistently ontop of the input.
=> Bug fix/config dialog

site/src/components/home/designer/countdown/countdown.jsx, site/src/components/home/designer/countdown/style.jsx, site/src/components/home/designer/designer.jsx, site/src/components/home/designer/effect/effect.jsx, site/src/context/effectsContext.jsx, site/src/util/time.js
* Added press enter to submit new time interval.
* Changed interval display in designer from ms to a time format.
* If interval Config < 1000ms it will show in ms and can be configured as 0.xxx seconds. anything 1s and above can be configured to second precision.  
A couple of other code cleanups. Fixed promises in chipRequests and fixed bad propTypes in effects.jsx
=> Interval input fixes

include/effects/matrix/PatternWeather.h
This Pull Request should close issue [256](https://github.com/PlummersSoftwareLLC/NightDriverStrip/issues/256).
- Ensure all API Calls are only done if API Key is present
- Ensure all methods only have one exit point
- Improve Debug message levels to match actual state
- Add improved method level comments
=> Refactor Weather API Function Calls

platformio.ini
=> Add warning suppressions for external libraries in 'pio check'.

.github/workflows/CI.yml, .github/workflows/release.yml, README.md
This makes some changes to the Action status badge(s) at the top of the README.
As the changes don't impact the project code, I will merge this without review if CI passes.
=> Update badges in README

include/deviceconfig.h
=> Don't require network credentials, etc. for non-networked builds.

include/soundanalyzer.h, platformio.ini, samples/videoserver/VideoServer2.py, samples/videoserver/videoserver.py
Upgrading the FastLED & arduinoFFT dependencies to the latest version. There were no breaking changes in more recent versions of FastLED so the upgrade was merely adding the caret in platform.ini, but arduinoFFT required a few code changes.
I believe they do
=> update arduinoFFT to ^2.0 and FastLED to ^3.8.0

src/drawing.cpp
I finally caught the bug that could cause the spectrum project to drop to 1FPS for a while, but only after days of running.  If the time of day clock gets adjusted backwards, we could pick up a large time delta that persisted.
=> Guard against clock underflow in drawing loop

config/web_projects.json
Update the web installer projects list: remove magicmirror
=> Prepare for release
