PlummersSoftwareLLC/NightDriverStrip

- include/globals.h
Just the removal of an extra character which snuck into the documentation.
> Fix documentation typo

- platformio.ini
This fixes the duplicated deps issue Dave mentioned in his video.
It does this by moving all common deps to a common section, and board specific deps to their own board specific section.
Then these sections are referenced in the env lib_deps and in env subsections where applicable. 
It also makes all deps use the same import format $group/$dependency @ $version_spec (this was just because the different formats was bothering me. I can revert if desired)
Also, I don't think Wire is a necessary dependency as the projects compile without it, so I've removed it.  
--
Also, on a side note: it looks like the spectrum example has code that only works on the M5Stick.  I had to comment these M5.Lcd lines from the spectrumeffects.h file to get the project to compile on the heltec_wifi_kit_32_v2 …
> Don't duplicate deps in platformio.ini; add heltec_wifi_kit_32_v2 board support

- .github/workflows/CI.yml
This adds the `m5plusdemo` and `heltecdemo` configurations to the CI workflow after the merge of #46.
> Add m5plusdemo and heltecdemo to CI build configs

- partitions_custom.csv
I made a few math errors in my previous PR modifying the partitions_custom.csv file. 
This PR fixes them, and enables the 4M storage partition by default. 
I have folks from the discord to thank for figuring this out. Thanks!
This was tested: 
```
> pio run --target uploadfs --environment demo
<snipped>
Building SPIFFS image from 'data' directory to .pio\build\demo\spiffs.bin
<snipped>
Auto-detected Flash size: 4MB
<snipped>
Environment    Status    Duration
-------------  --------  ------------
demo           SUCCESS   00:00:11.208
```
> Fix math error in partitions_custom.csv, enable 4M storage partition by default

- include/effects/spectrumeffects.h
- include/globals.h
- platformio.ini
- src/effects.cpp
The purpose of this PR to fix the brooklynroom project's build errors. I also added a brooklynroom env in the platformio.ini file so the project can be added to the github CI if desired. 
Here are the build issues and how I solved them. So we're clear, I'm not sure these are the best ways to solve these issues. 
1) The FAN_SIZE setting for this project was previously set to NUM_LEDS, but there is no matching definition in faneffects.h for a FAN_SIZE > 16. This causes FanPixelsVertical not to be declared.   To solve this build error I have set the FAN_SIZE to 1 for the project in globals.h. 
2) I added #if USE_TFT sections around the M5 LCD update code in spectrumeffects.h to allow it to build on both heltec and m5 boards. I think this makes sense as NightDriverStrip is supposed to support …
> Draft: Fix brooklynroom project build

- include/effects/faneffects.h
- include/globals.h
- platformio.ini
- src/effects.cpp
- src/main.cpp
This config is made to drive a 5x5x5 LED cube.
The used LEDs use RGB instead of GRB, hence the requirement to change the color order.
Using the insulator effects, each layer of the cube represents one "insulator", which generates especially with the spectrum effect some nice 3D effects
> Add RGB Cube configuration

- data/index.html
Adds a .click() event handler to the checkboxes in index.html. 
When a checkbox is checked, EnableEffect() is called, otherwise DisableEffect() is called.
> Add .click() handler to webserver checkboxes

- include/effects/effectmanager.h
With this fix, disabling all effects will now:
- Immediately turn off all LEDs
- No longer get stuck in NextEffect()
This partially addresses [Issue #90](https://github.com/PlummersSoftwareLLC/NightDriverStrip/issues/90).
> Count enabled effects

- .github/workflows/CI.yml
- lib/README.md
- platformio.ini
This removes the need for the CI to download the dependencies for each project build. 
It also separates the builds into their own steps to make it easier to see which failed. 
This has a nice side-effect of decreasing the amount of time it takes for the CI to complete by about 1-2 minutes.
> CI: Install platformio framework and libdeps before builds, seperate ci build steps

- .github/workflows/CI.yml
- include/globals.h
- src/effects.cpp
This:
- converts the `mult` and `glob` variables that were added in #75 into globals.h `#define`s.
- adds the brooklynroom and ledstrip (#81) configurations to the CI workflow.
- removed the treeset config from CI, based on [a comment on PR #95](https://github.com/PlummersSoftwareLLC/NightDriverStrip/pull/95#issuecomment-980639164).
> Fix StarryNight variables

- data/index.html
- include/spiffswebserver.h
This feature was designed to address parts of [Issue #90](https://github.com/PlummersSoftwareLLC/NightDriverStrip/issues/90). The goal was to improve the visual feedback on the web page in a number of ways:
- The currently running effect will automatically appear selected (without triggering the selected event)
- A new status bar is included below the list of effects:
- The left side displays the name of the currently running effect and a progress bar showing the amount of time remaining for that effect
- The right side shows a count of currently enabled effects
- This information is updated on the web page every 2 seconds by polling the /getEffectList endpoint in RequestEffectList()
> FEATURE: Webserver: Current Effect Status

- include/globals.h
- include/screen.h
- platformio.ini
- src/effects.cpp
- src/main.cpp
- src/screen.cpp
Fixes the build break for configs with no screen like brooklynroom
> Fix brooklynroom break

- src/screen.cpp
When a effect name has more than 18 characters, the name gets cut off.
This switches the text size to small if the name has more than 18 characters
> Fix effect text size when effect name is longer than 18 characters

- include/globals.h
- include/ledbuffer.h
- include/ntptimeclient.h
- include/socketserver.h
- platformio.ini
- src/drawing.cpp
- src/network.cpp
- src/screen.cpp
Adds a "ResponsePacket" that is sent back to the host every time we receive a data frame.  This packet includes information like our firmware version, current FPS, buffer size, buffer pos, and so on.
* [Xttp://github.com/PlummersSoftwareLLC/NightDriverStrip/blob/main/CONTRIBUTING.md).
* [ X] I understand the BlinkenPerBit metric, and maximized it in this PR.
* [ X] I selected `main` as the target branch.
* [X ] All code herein is subjected to the license terms in [COPYING.txt](http://github.com/PlummersSoftwareLLC/NightDriverStrip/blob/main/COPYING.txt).
> Enable response packet over sockets to give server our current status

- include/effects/faneffects.h
- src/effects.cpp
Implements HueFireFanEffect, a replacement for existing BlueFireFanEffect and GreenFireFanEffect that allows for easy access to many more color options.
Removed BlueFireFanEffect and GreenFireFanEffect.
Fixed up effects.cpp to reflect changes. Didn't add any new colors as examples, but usage is clear from existing, re-worked effect entries.
> Implement HueFireFanEffect class. Removed GreenFireFanEffect and BlueFireFanEffect classes.

- include/effects/strip/misceffects.h
This is an alternative solution for the issue addressed in #146. It has also been written to align with the current state of the codebase (after the merge of #150).
> TwinkleEffect: Check selected pixel isn't already lit

- include/effectmanager.h
- include/effects/strip/meteoreffect.h
- include/effects/strip/stareffect.h
- include/spiffswebserver.h
When ENABLE_AUDIO is set to 0, stareffect.h and meteoreffect.h have compilation errors because of gVURatio being referenced.
The web server also fails to build when ENABLE_AUDIO is 0.
Finally, a remote effect fails to build when ENABLE_AUDIO is 0.
> Cleanup "ENABLE_AUDIO" bugs

- include/network.h
- include/socketserver.h
- src/main.cpp
- src/network.cpp
Add Wifi status to Heartbeat. Updating WIFI_ENABLED usage to remove unrequired dependent capabilities.
- Add Wifi Status to Heartbeat; Useful for my use-case where various issues cause loss of access and this helps diagnose.
- Optimized pre-processing of network.h/.cpp when WIFI_ENABLED is disabled.
- Add  WIFI_ENABLED checks where required/necessary on transitive dependencies. i.e. #if ENABLE_WIFI && INCOMING_WIFI_ENABLED
- Samples from WIFI_ENABLED|AUDIO_ENABLED * 0|1 against single env.
----
audio, wifi
(I) (loop)(C1) Wifi: WL_CONNECTED, IP: 10.0.0.41, Mem: 46088, LargestBlk: 40948, PSRAM Free: 0/0, Buffer: 46/7, LED FPS: 0, LED Watt: 1079574528, LED Brite: 0%, Audio FPS: 0, Serial FPS: 1086324736, PeakVU: 0.00, MinVU: 1.00, VURatio: 1.20, CPU: 06%, 00%, FreeDraw: -1.407352
----
audio, …
> Small Wifi module optimization and improvements.

- .github/workflows/CI.yml
- README.md
- config/manifest_template.json
Now that the SPIFFS partition is no longer used to hold the content for the on-device website, there is no remaining need to build or flash it. This PR removes:
- The SPIFFS image from the web installer manifest template
- The `pio run -t buildfs` step from CI
- The README.md section that discusses how to build and upload the SPIFFS image with the website contents
> Remove SPIFFS flash

- .gitignore
- include/globals.h
- platformio.ini
Lilygo T-Display-S3 config was added to platform.io to make it easy to compile for this platform.
* [*] I read the contribution guidelines in [CONTRIBUTING.md](http://github.com/PlummersSoftwareLLC/NightDriverStrip/blob/main/CONTRIBUTING.md).
* [*] I understand the BlinkenPerBit metric, and maximized it in this PR.
* [*] I selected `main` as the target branch.
* [*] All code herein is subjected to the license terms in [COPYING.txt](http://github.com/PlummersSoftwareLLC/NightDriverStrip/blob/main/COPYING.txt).
> added Lilygo T-Display-S3 config

- site/package.json
- site/yarn.lock
Removes the single quotes around `npm run build` from the `rebuild` script in site/package.json. At least on Windows this is required to make `npm run rebuild` and hence `npm run start` work.
> Fix package.json rebuild script

- platformio.ini
This updates the GitHub URL used to pull in the SmartMatrix dependency in the Mesmerizer platformIo.ini configurations.
> Update SmartMatrix GitHub URL

- include/effectmanager.h
- src/main.cpp
This PR improves the JSON (de)serialization of EffectManager. Specifically, it:
- Fixes a bug in the saving of the effect enabled state
- Also saves the effect interval
- Saves the EffectManager config after an update to effect enabled state or effect interval via the respective EffectManager methods
> Extend and fix saving of EffectManager config

- README.md
- REST_API.md
- include/deviceconfig.h
- include/effectmanager.h
- include/effects/matrix/PatternPongClock.h
- include/effects/matrix/PatternSubscribers.h
- include/effects/matrix/PatternWeather.h
- include/effects/matrix/spectrumeffects.h
- include/effects/strip/bouncingballeffect.h
- include/effects/strip/doublepaletteeffect.h
- include/effects/strip/faneffects.h
- include/effects/strip/fireeffect.h
- include/effects/strip/laserline.h
- include/effects/strip/meteoreffect.h
- include/effects/strip/misceffects.h
- include/effects/strip/paletteeffect.h
- include/effects/strip/particles.h
- include/effects/strip/snakeeffect.h
- include/effects/strip/stareffect.h
- include/globals.h
- include/ledstripeffect.h
- include/webserver.h
- platformio.ini
- site/src/components/home/designer/designer.jsx
- site/src/components/home/statistics/stats.jsx
- src/deviceconfig.cpp
- src/effects.cpp
- src/main.cpp
- src/webserver.cpp
- tools/NightDriverStrip.postman_collection.json
This:
- Makes the YouTube channel GUID and name, as used by the Subscriber effect, configurable using DeviceConfig
- Adds the ability to have individual settings validated by POSTing them to the /settings/validated sub-endpoint
- Hides sensitive settings when returning the configuration on the /settings endpoint
- Adds the `override` specifier to JSON-related functions
- Documents the API published by the built-in webserver
- Provides a Postman collection file to facilitate the use of the on-device API
Because of the first point, this fixes #261.
> Subscriber configurability, sensitive and validated settings, documentation

- README.md
- REST_API.md
- include/deviceconfig.h
- include/effectmanager.h
- include/jsonserializer.h
- include/ntptimeclient.h
- include/secrets.example.h
- src/deviceconfig.cpp
- src/effects.cpp
- src/jsonserializer.cpp
- src/main.cpp
- src/webserver.cpp
- tools/NightDriverStrip.postman_collection.json
This:
- makes the NTP server used for clock synchronization configurable via the /settings endpoint.
- parallelizes JSON writes to SPIFFS
> Make NTP server configurable & JSON writes parallel

- README.md
Add notes on JSON effect persistence to README.md. This is triggered by #271 and #281.
> Add JSON notes to README.md

- REST_API.md
- include/effectmanager.h
- include/webserver.h
- platformio.ini
- src/webserver.cpp
- tools/NightDriverStrip.postman_collection.json
This adds the ability to change the order of the effects in the effects list, and exposes it in an endpoint to which the current and newly desired effect indices can be passed. Any effect order changes made are persisted across reboots.
The API documentation and the Postman collection file have been extended accordingly.
> Make effects movable via the API

- README.md
- REST_API.md
- include/effectmanager.h
- include/effects.h
- include/effects/matrix/PatternSubscribers.h
- include/effects/matrix/PatternWeather.h
- include/effects/strip/bouncingballeffect.h
- include/effects/strip/faneffects.h
- include/effects/strip/fireeffect.h
- include/effects/strip/meteoreffect.h
- include/effects/strip/misceffects.h
- include/globals.h
- include/jsonserializer.h
- include/ledstripeffect.h
- include/types.h
- include/webserver.h
- src/effects.cpp
- src/jsonserializer.cpp
- src/webserver.cpp
- tools/NightDriverStrip.postman_collection.json
This:
- Exposes the friendly name and maximum effect time as settings of LEDStripEffect (and as such, any derived effect in principle).
- Adds the API-exposed ability to create a copy of an existing effect, optionally with modified settings from the original.
- Adds the API-exposed ability to delete a previously created copied effect.
- Updates documentation and Postman collection file accordingly.
> Expose LEDStripEffect settings, copy effects and remove copies

- include/deviceconfig.h
- include/effectmanager.h
- include/jsonserializer.h
- include/socketserver.h
- include/types.h
- src/deviceconfig.cpp
- src/effects.cpp
- src/jsonserializer.cpp
- src/webserver.cpp
- tools/NightDriverStrip.postman_collection.json
This:
- Isolates the saving/storage of the current effect index from the rest of the effects config
- Makes enabling/disabling the saving (remembering) of the current effect (index) a device setting
> Isolate current effect save

- src/deviceconfig.cpp
Was String, I think it should be Boolean to match the other flags.
Noticed that the rememberCurrentEffect Setting Spec Type was not boolean as are the other flag settings.
> Correct the Setting Spec Type of rememberCurrentEffect

- platformio.ini
One hard-coded `upload_port` escaped my review on earlier in-fork merges.
> Remove upload_port from platformio.ini

- src/main.cpp
- src/network.cpp
> Use c_str() where appropriate when printing hostnames at startup.

- include/effects/matrix/PatternBounce.h
- include/effects/matrix/PatternClock.h
- include/effects/matrix/PatternFlowField.h
- include/effects/matrix/PatternMisc.h
- include/effects/matrix/PatternPongClock.h
- include/effects/matrix/PatternPulse.h
- include/effects/matrix/PatternSwirl.h
- include/effects/matrix/PatternWave.h
- include/gfxbase.h
- include/ledmatrixgfx.h
- include/taskmgr.h
- platformio.ini
- src/main.cpp
Increases stack size to prevent S3 from crashing in JSONWriter
Makes writing out of pixel bounds at least an error message
Adds DrawSafeCircle which doesn't assume it's OK to write out of bounds
Fixes a number of effects that did write out of bounds
> Fix S3 crash, make invalid pixel draws errors

- config/partitions_custom_8M.csv
- include/effectmanager.h
- include/globals.h
- include/taskmgr.h
- platformio.ini
- src/drawing.cpp
- src/main.cpp
- src/network.cpp
8M Flash, 60Hz, enable OTA, improve OTA
Adds new partition tabe file with 8M suffice for mesmerizer that makes use of 8M of flash, which makes enough room for a second OTA partition.
> 8M Flash, 60Hz, enable OTA, improve OTA

- include/effectmanager.h
- include/effects/matrix/PatternMisc.h
- include/effects/strip/faneffects.h
- include/gfxbase.h
- include/globals.h
- include/improvserial.h
- include/ledmatrixgfx.h
- include/ledstripgfx.h
- include/network.h
- include/systemcontainer.h
- platformio.ini
- src/drawing.cpp
- src/effects.cpp
- src/ledmatrixgfx.cpp
- src/ledstripgfx.cpp
- src/main.cpp
- src/network.cpp
- src/remotecontrol.cpp
This fixes #349, to the extent #365 hadn't already. It does this by:
- Adding PrepareFrame() and PostProcessFrame() virtual functions to `GFXBase`
- Overloading both in `LEDMatrixGFX`
- Overloading PostProcessFrame() in `LEDStripGFX`
These changes have been tested on a Mesmerizer board running Mesmerizer, and an M5StickCPlus running Spectrum.
Also, this:
- Declares globally defined variables that are actually only meant to be used by one compilation unit (.cpp file) `static` and gives them an `l_` prefix (instead of `g_` for "true" globals).
- Fixes a regression that NTP time was no longer updated at regular intervals.
**Note:** I am aware this PR will cause merge conflicts with #369. I will address these when either that PR or this one has been merged. I'm opening this now so people can …
> Add PrepareFrame() and PostProcessFrame() to GFXBase and subclasses

- include/effects/matrix/PatternCube.h
- include/effects/matrix/spectrumeffects.h
- include/gfxbase.h
- include/globals.h
- include/ledmatrixgfx.h
- include/soundanalyzer.h
- include/taskmgr.h
- platformio.ini
- samples/videoserver/videoserver.py
- src/main.cpp
I found a case where PatternCube was getting bit by the watchdog, and it turned out BresenhamLine was never returning.  That turns out to be a bug in the base library we inherited.  Instead of accumulating the error over several passes, it was resetting it every time, and that doesn't always work.  Now it does.
Also fixes an issue with SpectrumBarEffect where it would display all-same-height bars.  I believe this was related to the decay rates not being set.  If it recurs, I'll reopen the issue.
I'm also enabling a heap check after each thread is created.  We can put this in ifdef DEBUG if preferred.
> Fix linedraw bug

- include/effects/matrix/PatternSpiro.h
This caught my eye while I was running over nearby code. The left and the
right of that || test were identical.
I chased the code through that gist through its origin git history through
git blame and this change went in with a description that was something
like "make more awesomer".
Removing it changes no behaviour. It just removes a nail that's poking
through the floor surface.
Tested: successful compilation on mesmerizer. Should compile everywhere
without change because it was already if (something || that_same_something).
> Eliminate duplicated test in PatternSpiro

- include/ledstripgfx.h
- src/socketserver.cpp
- Format specifier fixes in socketserver
- Format specifier fixes in socketserver
- Specifier fixes in ledstrip
More Correctness fixes in specifiers.
> Improve logging on where signal is going, Various specifier fixes

- README.md
- include/effectdependencies.h
- include/effectmanager.h
- include/effects/matrix/PatternFlowField.h
- include/effects/matrix/PatternMandala.h
- include/effects/strip/misceffects.h
- include/gfxbase.h
- include/globals.h
- include/ledmatrixgfx.h
- include/ledstripeffect.h
- include/values.h
- platformio.ini
- src/effects.cpp
- src/ledmatrixgfx.cpp
- src/main.cpp
- src/network.cpp
Addressed most concerns in https://github.com/PlummersSoftwareLLC/NightDriverStrip/discussions/390
- Fix issue 1 about PIN0 naming.
- Fix issue 2 about DEMO overdrawing by a factor of 8.
- Let device names reflect LED electrical types (HUB75, NeoPixel) and not physical orientation (MATRIX, STRIP). Build SPECTRUM uses NeoPixels, but in a MATRIX, for example. HEIGHT > 1 can be used for "grid-ness" of those builds, but it was never used as such.
Issue 3 on what RINGS are, how a line has five of them, and why it's ever
appropriate to be equal to NUM_LEDS remains open.
All are in separate submits if you want to cherry pick.
I tried to preserve the mixture of DOS and UNIX NL conventions.
> Address issues raised in issue 390

- include/improvserial.h
- include/network.h
- src/main.cpp
- src/network.cpp
- src/screen.cpp
This fixes #371 by waiting for WiFi credentials indefinitely if they are not set and WiFi is required. This is to cater for the case that the LEDSTRIP project is flashed using the Web Installer, which sets the SSID to an empty string. 
If an invalid set of credentials is set, then the device will eventually reboot - as it currently does immediately if no WiFi credentials are available. Due to the 99 attempts with incremental waits, it will take about an hour and a half (5247 seconds) before the code reaches that point. Which gives sufficient opportunity to correct a typo in SSID or password if one realizes one was made.
> Wait for WiFi credentials if not set

- include/effectdependencies.h
- include/globals.h
- src/main.cpp
- src/network.cpp
This follows up PRs #394 and #395, in the sense that:
- USE_NEOPIXEL is renamed to USE_WS281X, in line with the conversation in #394's comments
- Constants are introduced for the WiFi waiting time in network.cpp's ConnectToWiFi(), in accordance with the review comment on #395
> PR #394 and #395 follow-up

- .github/workflows/CI.yml
- include/ntptimeclient.h
- src/network.cpp
- src/ntptimeclient.cpp
I've had this in my tree for a while, but while soaking the new effects,
it's actually justified its bits per blinken, IMO.
Help text:
(processRemoteDebugCmd)(C1) uptime              Show system uptime, reset reason
Sample invocation:
uptime
* Debug: Command received: uptime
(I) (ShowUptime)(C1) Uptime: 0 days - 00:04:50
(I) (ShowUptime)(C1) Last boot reason: Power On
(I) (loop)(C1) Here
(I) (esp32_partition_table_read)(C1) Reading partitions
(I) (esp32_partition_table_read)(C1) nvs 36864 8192
It's quite ESP32-specific in some ways and it's definitely force-fit
into ntpclient (hey, it's gotta be somewhere, right?) but I really don't
think it's any weirder or less justified that a lot of the existing
code.
I had a version of this that displayed the uptime in an overlay, but it
destroyed …
> [Quality of Developer Life] Add a new telnet/serial debugger command: uptime.

- include/globals.h
- include/remotecontrol.h
- src/main.cpp
- src/screen.cpp
- Make USE_REMOTE and USE_BUTTON more self-contained.
- Missing file from previous commit.
IMO, this change stands on its own as just good style of constraining
the code that uses remote into the files and blocks that use remote.
More motivationally, the remote code is Really Annoying to build. It's
a lot of files to compile in the hope that -ffunction-sections will
actually throw them away. Better to simply not compile them. This makes
that possible.
With this change, it's possble to lib_ignore Bounce2 and IRremoteESP8266
(and U8g2 and QRcode...) these modules, though I haven't reconciled how
to do so against our recommended document and style. As such, the change
that REALLY takes advantage of this,
+lib_ignore  = U8g2
+       Bounce2
+       IRremoteESP8266
+       QRCode
+board = …
> Make USE_REMOTE and USE_BUTTONS_ more atomic

- WebInstaller/index.html
This fixes the "sidenote issue" mentioned in #425, that being that the Web Installer does not allow scrolling when the Web Installer page doesn't fit in the browser window, like when a larger font size is chosen.
> Fix Web Installer overflow handling

- include/ledstripgfx.h
If a developer put LED_PINn on pins 4, 12, 13, 14, 15, this would have ensured that no data would have ever left the chip. PIN5 would have been OK only because this code "accidientally"? missed it.
I'm highly suspicious of this code and doubt that any of us can test it and prove it's correct, we can only inspect it and reason that it's wrong.
Do you agree that it's wrong?
> Remove code setting common GPIOS to inputs when ATOMLIGHT ledstripgfx.h

- src/ledstripgfx.cpp
Recently a device brightness level was added. This code takes advantage of that by applying it to led strip pixels just before they are displayed by FastLED. 
After the pixels are added to FastLED, we iterate each one and apply the system level brightness. This only applies to regular strip effects, and not to matrices. If you notice it is actually calling the fadeLightBy method of the CRGB color object. So we are actually passing an inverse of the brightness level.
The awesomeness of this is that a person can set the global brightness and not cause eye pain to themselves or loved ones, especially when working with lights at night.
> Updated ledstripgfx.cpp to apply system brightness to pixels.

- include/effects/matrix/PatternSMNoise.h
- include/effects/matrix/PatternSMPicasso3in1.h
- include/effects/matrix/spectrumeffects.h
- include/effects/strip/faneffects.h
- include/effects/strip/fireeffect.h
- include/effects/strip/laserline.h
- include/effects/strip/misceffects.h
- include/ledstripeffect.h
This increases the smallest JSON buffer size used for effect serialization from 128 to 192 bytes. It seems that the introduction of the "mi" property in #454 makes that some effects that serialize additional properties (like RainbowFillEffect) now run out of buffer space, meaning properties get lost while serializing. 
As such, this PR fixes #457. 
Thanks to @revision29 for reporting this.
> Bump smallest effect JSON buffer size to 192 bytes

- README.md
- include/effects/matrix/PatternSubscribers.h
- include/effects/strip/bouncingballeffect.h
- include/effects/strip/fireeffect.h
- include/effects/strip/meteoreffect.h
- include/effects/strip/misceffects.h
- include/globals.h
- include/ledstripeffect.h
- src/screen.cpp
- src/webserver.cpp
This implements a small number of tiny fixes that were triggered by recent changes or conversations.  
Concretely:
- It changes the way effects calculate the memory they need to reserve to serialize themselves to JSON.
- It fixes an invalid `NUM_INFO_PAGES` define for TTGO.
- It removes defines of `ONSCREEN_SPECTRUM_PAGE` from globals.h, because it is no longer used anywhere.
- It sanitizes the value of `NUM_INFO_PAGES` down to the values that are actually valid for screen.cpp (1 or 2).
- It replaces an index-based for loop in webserver.cpp by a range-based one, which makes more sense at that spot.
> Some tiny fixes

- include/deviceconfig.h
- include/effects/matrix/PatternSMNoise.h
- include/effects/matrix/PatternSMPicasso3in1.h
- include/effects/matrix/PatternSubscribers.h
- include/effects/matrix/spectrumeffects.h
- include/effects/strip/bouncingballeffect.h
- include/effects/strip/faneffects.h
- include/effects/strip/fireeffect.h
- include/effects/strip/laserline.h
- include/effects/strip/meteoreffect.h
- include/effects/strip/misceffects.h
- include/ledstripeffect.h
- platformio.ini
- src/deviceconfig.cpp
- src/webserver.cpp
While looking into the documentation concerning the upgrade from ArduinoJson version 6 to 7 in follow up to #463, I found that in ArduinoJson version 6.17, a function `JsonDocument::overflowed()` was introduced that indicates if the JSON buffer that was reserved for the document ran out of space during serialization. 
This PR checks for this condition, and:
- aborts through `assert()` in cases an incomplete JSON serialization impacts the core functionality of the project, or
- logs an error in cases where it doesn't. This is the case if it concerns objects that are returned by the web API.
Although this doesn't take the guesswork out of the buffer size to allocate, it does flag when that size turns out to be too small.
Finally, I've replaced JSON buffer size literals with a `_jsonSize` …
> Check for JSON buffer overflows

- include/effectmanager.h
- include/effects/matrix/spectrumeffects.h
- include/effects/strip/doublepaletteeffect.h
- include/effects/strip/faneffects.h
- include/effects/strip/fireeffect.h
- include/effects/strip/paletteeffect.h
- include/effects/strip/particles.h
- include/effects/strip/snakeeffect.h
- include/effects/strip/stareffect.h
- src/audio.cpp
- src/drawing.cpp
- src/effectmanager.cpp
- src/effects.cpp
- src/main.cpp
- src/network.cpp
- src/screen.cpp
- src/webserver.cpp
This:
- Applies JSON buffer overflow checking to more places, in follow up to #466 - and actually complete that implementation across all effects.
- Makes the link between `EffectManager`'s declaration and certain effects cleaner, thereby preventing circular dependency problems that have otherwise known to occur (as illustrated in the discussion of #456). It also makes the inclusion of "soundanalyzer.h" more explicit in source files that need it.
> More small fixes

- config/web_projects.json
- include/deviceconfig.h
- include/globals.h
- include/improvserial.h
- include/network.h
- include/secrets.example.h
- include/types.h
- include/webserver.h
- platformio.ini
- site/src/index.html
- src/main.cpp
- src/network.cpp
- src/webserver.cpp
- tools/NightDriverStrip.postman_collection.json
This:
- Changes the WiFi connection logic to not block the main `setup()` function.
- Makes the stored WiFI credentials (which we consider sensitive) local to the only function that really uses them, instead of global variables that are available "everywhere".
- Maintains the possibility to demand functioning WiFi connectivity at the penalty of a reboot if it's down for too long.
- Makes the hostname a device config setting, and makes the hostname consistent across use cases (WiFi, OTA, RemoteDebug).
- Significantly improves the logging of Improv traffic to SPIFFS when enabled, to the point it is actually usable to analyze issues with Improv processing.
- Fixes #425.
- Makes index.html link to index.js instead of index.js.gz, to prevent fetch errors for the latter.
- Includes a small …
> Update WiFi connection logic and improve Improv logging

- include/improv.h
- src/improv.cpp
Was replaced by parse_improv_serial_byte_() that's class-local.
Tested: local run on Demo, Mesmerizer.
Successful buddy build.
As is appropriate for this Haloween night, it's thoroughly and completely dead.
> Remove uncalled function, proto for parse_improv_serial_byte

- include/effects/matrix/PatternSMSupernova.h
drawPixelXYF() was merging pixels from the VU meter t othe bottom of the
line, so if there was sound in the room, red and green smears appared.
Fixed by making it better obey the HEIGHT values and compensating for
VU.
Follow through on my whining to make it look (more) like it was written
by a programmer.  Generated assembly code is now beautiful with
references carrying values across methods. Data is now per-Blob,
sequentially accessed, and in a std::array.
More importantly, memory is accessed sequentially and locally, just
like read-ahead and paging systems like.  Most accesses should be
cache hits now.
These various minor optimizations resultign in 12 FPS improvement
according to self-reporting. It _looks_ fast.
Fixes #446.
Tested with asserts() inserted for out-of-bounds pixel …
> Supernova: dont merge pixels from VU meter at top of screen to bottom.

- include/effects/matrix/PatternSubscribers.h
This fixes a bug in the Subscribers effect due to which the settings in the LEDStripEffect base class were not returned. More precisely phrased they were serialized, but then overwritten by the settings specific to PatternSubscribers.
> Fix Subscribers effect settings serialization bug

- site/src/components/home/config/configDialog.jsx
Fixed #472 Added support for `emptyAllowed` configurations to be saved.
Fixed #476 Added support for configuration to limit between min and max values for numeric input types. If no min/max is set the dataTypes min/max is used as a proxy.
> Config dialog improvements

- include/globals.h
This changes the feature flags of the Spectrum build configuration to allow the web server to be started and working - this currently doesn't work due to low memory conditions on some devices at least.
This is mainly for the purposes of the Web Installer; I consider it more likely that Web Installer users want to use the on-chip webserver than the services/features that have now been disabled. People who make and flash local builds can easily customize the build configuration in globals.h to their own liking, anyway.
> Reconfigure Spectrum builds

- include/effects/matrix/PatternSMSupernova.h
This fixes #510. The main change is that the effect makes a clean start every run, as it used to before #489 was merged. I've also:
- Cleaned up a few (more) things that didn't seem to serve any purpose.
- Reinstated the use of `g()->isValidPixel()` to check if we're using sane x and y values, and skipping the draw otherwise.
- Added a check that only avoids sampling VU meter pixels if we're actually showing it.
> Fix Supernova effect

- include/globals.h
- include/jsonserializer.h
- src/deviceconfig.cpp
- src/effectmanager.cpp
- src/jsonserializer.cpp
- src/network.cpp
Added code to catch instances where SerializeWithBufferSize gets into an *infinite fail loop. Adjusted SaveToJSONFile to handle SerializeWithBufferSize failing.
There are times when a serializer fails to allocate memory for pJsonDoc. The SerializeWithBufferSize function interprets this as the JSON document needing more buffer. That might be the case sometimes, but it does not handle cases when the device runs out of usable memory. This code change keeps the buffer size adjustment, but adds code to handle the case where the device can't allocate memory for the JSON document.
The code allows for the allocation in SerializeWithBufferSize to fail 5 times before it stops trying. Once it stops trying it exits the loop. When SaveToJSONFile continues, it will have to handle having either a null …
> Update jsonserializer.cpp to break infinite fail

- include/globals.h
- Fix crash on "large" configurations, especially on ESP32-S3.
See  https://github.com/PlummersSoftwareLLC/NightDriverStrip/issues/515 for the (painful) details.
Fixes #515.
> Fix crash on "large" configurations, especially on ESP32-S3.

- include/effects/matrix/PatternSMBlurringColors.h
This fixes the Powder/`PatternSMBlurringColors` effect, which could get stuck with one color-fluctuating pixel in the lower-left corner of the matrix (technically the one pixel would "radiate" a little outwards, but who's looking that closely?)  
As with `PatternSMSupernova` before, the main issue seems to be that the effect needs to always start with an empty set of, in this case, `trackingObject...` arrays to ensure it has a usable working set of pixels to evolve. 
I note for the record that this effect would definitely benefit from an overall clean-up and OOP overhaul like the one that `PatternSMSupernova` received in #489. For the benefit of getting the effect to work the way it should as quickly as possible, in this PR I decided to focus purely on setting up the start-up conditions …
> Fix Powder/PatternSMBlurringColors effect

- include/effects/matrix/PatternSMFire2021.h
- include/effects/matrix/PatternSMHolidayLights.h
- include/effects/matrix/PatternSMHypnosis.h
- include/effects/matrix/PatternSMNoise.h
- include/effects/matrix/PatternSMPicasso3in1.h
- include/effects/matrix/PatternSMRadialFire.h
- include/effects/matrix/PatternSMRadialWave.h
- include/effects/matrix/PatternSMRainbowTunnel.h
- include/effects/matrix/PatternSMSmoke.h
- include/effects/matrix/PatternSMSpiroPulse.h
- include/effects/matrix/PatternSMStarDeep.h
- include/effects/matrix/PatternSMStrobeDiffusion.h
Force initialization of anything in the SM patterns to zero.
> Force-initialize class members to zero in SM effects.

- include/deviceconfig.h
- include/effectmanager.h
- platformio.ini
- src/effectmanager.cpp
- src/webserver.cpp
This adds a persisted device setting for showing or hiding the VU meter on matrix/audio builds, and exposes it via the web UI. This was suggested in #523, and mentioned in (an) earlier discussion(s). For completeness, the `SHOW_VU_METER` build flag is _not_ removed; the existing feature to toggle the VU meter via the IR remote control is now also available via the web UI and persisted across reboots.
In line with the original implementation in EffectManager, the show VU meter toggle can be (un)set without `SHOW_VU_METER` being defined, but persisting and publishing/showing it in the web UI only happens with that flag set.
Furthermore, `SHOW_VU_METER` is now also defined for the `mesmerizer_lolin` env in platformio.ini.
Tested on Mesmerizer.
> Add persisted "show VU" setting to web UI

- include/effects/matrix/PatternSMSmoke.h
This updates the SMSmoke effect to remove the tear/"pepper in fire" that was added in #450. As such, fixes #486.
> Remove tear/pepper in fire from SMSmoke

- include/globals.h
- Allow checking of format arguments against arguments in str_sprintf.
>  Allow checking of format arguments against arguments in str_sprintf.

- include/effects/strip/misceffects.h
Tweaked ColorFillEffect to optionally ignore global color
Instead of creating a new color fill effect that ignores the global color, I tweaked the existing effect to optionally ignore.
I also updated the label comment for the effect since it was wrong.
> Tweaked ColorFillEffect to optionally ignore global color

- src/effects.cpp
Adds the new animated GIF effects in disabled state, to prevent the crashes reported in #547. This is a workaround that still allows testing, until the root cause of the crashes has been found and fixed.
> Add Animated GIFs in disabled state

- README.md
- include/effects/matrix/PatternAnimatedGIF.h
- platformio.ini
- src/effects.cpp
Fixes crashes caused by the animated GIF effects introduced in #550. Pushes the animated GIF effects to their proper place. Adds build times to README for current project config.
> Fix animated GIF effects

- include/effects/matrix/PatternAnimatedGIF.h
- include/effects/matrix/PatternSMFire2021.h
- src/effects.cpp
Code now checks to see if GIF was loaded before trying to render it.
Improved fire perf
> Fix fire perf, protect against possible GIF load failure

- include/network.h
- include/webserver.h
- src/audio.cpp
- src/main.cpp
- src/network.cpp
Instead of scattering port numbers in source, headers, or macros, we
stuff them into one grep-able enum.
Tested:
Touch test on (out-of-tree) Demo project with webserver, debugger turned on.
Successful buddybuild
Not tested:
Commodore pet rock. (Wat!?!)
> Centralize port numbers in source

- include/deviceconfig.h
When new fields are added in the example file, add a test in the
file that uses the real file to be sure the fields are present. This
is to solve the case where a developer has a checked-out, working tree
with a working secrets.h, syncs to head or another branch that adds
fields in secrets, and then incurs weird compilation errors when those
new fields aren't found.
This change leads the developer to the correct file and the doc
describing it for a better experience.
As discussed in #572.
> Make secrets.h more immune to changes from secrets.example.h

- include/effectmanager.h
This fixes #583 by not lazily relying on an unsigned underflow when preparing `_iCurrentEffect` for the first "proper" effect after the splash logo.
> Fix hang in `PreviousEffect()` (issue #583)

- config/web_projects.json
- include/globals.h
This:
- Re-enables networking and the webserver in the Fanset config. This is possible since some of the latest dependency updates have yielded back a big part of the RAM we've seen disappearing in recent times.
- Moves the TTGO config to its own device in the Web Installer, to avoid it being flashed on more generic ESP32 devices inadvertently.
> Re-enable Fanset networking, move TTGO in web installer

- include/improvserial.h
This fixes #596, which documents a case where the sending of the Improv state packet to indicate we're up blocks setup, and hence the starting of the blinking of LEDs. It does this by moving the one-time sending of the packet from `ImprovSerial::setup()` to `ImprovSerial::loop()`.
> Move Improv announcement from setup to loop

- include/globals.h
- src/ledstripgfx.cpp
In follow up to a conversation in #601, this removes the definition of POWER_LIMIT_MW by default, and indeed allows it to not be set. 
If it is defined, it will still be respected in the same way it is now. 
If and when this PR is merged, it will replace and thus close #601.
> Don't define POWER_LIMIT_MW by default

- include/globals.h
- platformio.ini
- src/webserver.cpp
- Adds build flags and a new base configuration to _optionally_ enable the React Web UI. 
When working with Heltec V3 boards, memory pressure is tight for HTTP requests memory due to the lack of PSRAM. The webserver is disabled by default but I figured it would be useful to allow users to be able to utilize the API endpoints without the need of the dedicated UI. 
(In my use-case I am building a standalone react app that can be self-hosted to manage many NightDriverStrip devices and I need API access but do not need the embedded UI)
I welcome any feedback on the platform IO build configuration as it is still pretty new to me and I want to make sure that I do not increase the build complexity too much
> Allow for web UI endpoints to be disabled during build

- config/web_projects.json
- platformio.ini
This makes the m5plusdemo config build for the M5StickC Plus once again, and adds a separate m5stackdemo config that targets the M5Stack Core2. Fixes #633.
> Make demo config available for M5StickC Plus and M5Stack Core2

- .github/workflows/CI.yml
- .github/workflows/release.yml
- .github/workflows/web_installer.yml
- config/installer_index.html
- tools/bake_installer.py
This updates the GitHub workflows to build and deploy the production web installer only when a release is published, instead of on every push to the main branch. 
This is in preparation for the upcoming 1.0 release of NightDriverStrip.
> Make Web Installer build and deploy on releases publication

- platformio.ini
Web-recreation of https://github.com/PlummersSoftwareLLC/NightDriverStrip/pull/658
FastLED used to use C style hints of 'register' that were deprecated long ago and the keyword was removed in C++17. There was a kludge that just defined register away.
FastLED was been updated (long ago) so this is no longer necessary. We can return this token to valid namespace.
This has been in my tree for many months and has survived buddybuilds and a variety of FastLED versions.
> Remove outdated kludge for FastLED's use of register.

- include/screen.h
- platformio.ini
- src/screen.cpp
Added new dev_heltec_wifi_lora_v3 device and helteclorav3demo environment.
Changed build flag for dev_heltc_wifi_v3 from -DWIFI_Kit_32=1 to -DWIFI_Kit_32_V3.
Both flags do the same thing but passing the later may help compatibility in the future.
Fixed line in screen.h to disable LoRa by default.
> Added heltec wifi lora v3 board

- include/socketserver.h
- samples/videoserver/pcstats.py
- src/ledmatrixgfx.cpp
- src/socketserver.cpp
Adds a new 64-bit sequence number to the response packet.
Fixes the WiFi delivery framerate issue that was limiting it to about 8fps
> Add client response sequence, fix framerate on WiFi delivery

- include/effects/matrix/PatternStocks.h
This closes #662 by making the effect compare against the previous day's close instead of today's open. It does this both in the numeric change shown, as in the graph underneath it.
There is still one "peculiarity" that people may notice, which is that the data points in the graph include after-hour trading, and we don't show this in the coloring of the graph (Google and other sources tend to show after-hour trading in a different color).
This means that the last data point for a calendar day may be positive (green) while the (correct) day change is negative, or vice versa. If we want to change this then we need the stockserver to indicate in its response to the effect what data points are outside of regular trading hours.
Also, the default host for the stockserver changed from davepl.com …
> Make Stock effect compare against previous day's close

- .github/workflows/CI.yml
- README.md
Adds a section to the README concerning COM port problems on the Windows platform.
It includes another minor change to the GitHub CI workflow file so it no longer uses jq's --argfile option, which is no longer available in jq on Ubuntu 24.04.
> Add section on COM problems to README

- include/gfxbase.h
Minor readability fixes in gfxbase.
Minor readability fixes in gfxbase.
setPalette: use STL to find entry in a table instead of nine separate
string compares. The functions above and below really should be combined
similarly.
BresenhamLine():
More faithful reproduction of published implementations.
Computes pixel index only once.
Since we're amplifying 'e2' term, no need to recheck y in each iteration.
Keep sign of err in the most commonlhy used form instead of double negativ
e.
Tested:   Run all effects on Mesmerizer hardware, our most demanding build of   that code.**
I know this isn't your favorite tyep of PR, but technically it DOES improve
BlinkenPerBit by taking fewer bits to do the same thing. Use of STL maximixes
SWE brain cell consumption: find() finds things. Smarter data. …
> Misc minor enhancements in gfxbase

- README.md
Adds a note at the top of the README where Mesmerizer kits can be purchased, to preemptively address questions from people wondering where they are.
> Add Mesmerizer kit note

- include/globals.h
- include/screen.h
- platformio.ini
- src/screen.cpp
Updated code to ensure consistent OLED display behavior among most supported Heltec boards.
This code builds/works as expected for the following device models, with no local modifications except to create/populate a secrets.h file:
- Heltec Wifi Kit 32 (V2): pio run -e heltecv2demo -t upload
- Heltec Wifi Kit 32 (V3): pio run -e heltecv3demo -t upload
- Heltec Wifi LoRa 32 (V3): pio run -e helteclorav3demo -t upload
The "CurrentEffectSummary" screen now displays correctly (i.e., legible, but monochrome) on all three devices.
Prior to my changes, the code on the main branch resulted in different behavior for each device:
- Heltec Wifi Kit 32 (V2): Screen flashes solid blocks of pixels briefly on device boot or whenever any would-be-displayed data updates (this prompted my discussion #692 …
> Fix OLED behavior on Heltec Wifi Kit 32 V2 and V3

- src/remotecontrol.cpp
As discussed in #690, on all projects except Mesmerizer, the OFF button on the remote control should act as an effective OFF button, by turning the brightness to 0 on one press. On Mesmerizer, the OFF button should gradually decrease the brightness of the matrix - this was the behavior for all projects before #660 got merged. 
Due to a check for the wrong define being set (`HUB75` instead of `USE_HUB75`) the OFF button now also turns down the brightness all the way on Mesmerizer.
This PR fixes that.
> Make IR remote OFF button dim gradually again on Mesmerizer

- include/webserver.h
- platformio.ini
- src/webserver.cpp
This changes the ESPAsyncWebserver web server dependency from a slightly modified version of the original version developed by [me-no-dev](https://github.com/me-no-dev/) (now archived) to the version maintained by the [ESP32Async](https://github.com/ESP32Async/) project. It also allows ESPAsyncWebserver to pull in its own version of AsyncTCP; that project also moved to ESP32Async.
Credits go to:
- @robertlipe for raising this in #690 
- @heidepiek for testing, and finding a completely unrelated bug in the process (see #694)
> Switch to ESP32Async/ESPAsyncWebserver

- site/src/index.html
This switches from unpkg.com to jsdelivr.com for retrieval of on-board web UI JavaScript dependencies. Unpkg.com has become very unstable in the past few weeks, responding with various errors in the 5xx range and even temporarily not having a domain registration.
> Replace unpkg with jsDelivr

- include/deviceconfig.h
- include/effects/matrix/PatternAnimatedGIF.h
- include/effects/matrix/PatternSMNoise.h
- include/effects/matrix/PatternSMPicasso3in1.h
- include/effects/matrix/PatternStocks.h
- include/effects/matrix/PatternSubscribers.h
- include/effects/matrix/spectrumeffects.h
- include/effects/strip/bouncingballeffect.h
- include/effects/strip/doublepaletteeffect.h
- include/effects/strip/faneffects.h
- include/effects/strip/fireeffect.h
- include/effects/strip/laserline.h
- include/effects/strip/meteoreffect.h
- include/effects/strip/misceffects.h
- include/effects/strip/paletteeffect.h
- include/effects/strip/particles.h
- include/effects/strip/snakeeffect.h
- include/effects/strip/stareffect.h
- include/jsonserializer.h
- include/ledstripeffect.h
- src/effectmanager.cpp
- src/jsonserializer.cpp
This improves the handling of ArduinoJSON serialization memory overflows. Instead of triggering a device reset in case a JSON serialization memory overflow condition occurs, an error is logged and the failed serialization attempt is abandoned.
> Improve JSON serialization memory overflow handling

- include/effects/matrix/spectrumeffects.h
This PR fixes the spectrum effects code where the white highlight bar is 1 pixel too long on all the spectrum effects that utilize it.
> Update spectrumeffects.h to fix hightlight bar length

- include/network.h
Redo #733 in clean workspace.
We have a "network.h".
The Arduino system has a "Network.h"
__has_include can't distinguish between the two.
Our network.h uses some things that are only declared in the system network.h
so we really should be including it first. But we'd have to fix a bunch
of callers with ugly conditionals.
Weirdly, we have some OTA paths that can include (our) network.h
before Arduino.h, so we have to go get the version explicitly.
With exactly this change to this file, the network code can build on both.
Other pieces are forthcoming.
This PR probably took 500 builds to work through...The failures are WEIRD.
The inclusion of mac_addr was always technically required, but works in both.
> Allow our network build to compile Arduino2 or Arduino 3

- include/socketserver.h
This applies the linguistic (natural language and C++) improvements to socketserver.h that were originally included in #648. I excluded them from that PR because I am not able to test them.
This means that as soon as _someone_ can confirm they have seen the socket server fully working on at least one device and at least one configuration(/project/environment) with these changes applied, they can be merged also.
> Apply socketserver.h improvements from (original) #648

- include/effects/strip/particles.h
- include/effects/strip/stareffect.h
This commit refactors several class template instantiations to leverage C++17's Class Template Argument Deduction (CTAD) feature. By removing redundant template arguments from constructor calls, the code becomes more concise and readable without altering its functionality.
Affected files:
- `include/effects/strip/particles.h`
- `include/effects/strip/stareffect.h`
Tested:
Imported from my branch. Survives a build-all and run.
> Refactor: Apply Class Template Argument Deduction (CTAD)

- config/web_projects.json
- include/effects/matrix/PatternMandala.h
- include/effects/matrix/PatternSMHypnosis.h
- include/effects/matrix/PatternSMRadialFire.h
- include/effects/matrix/PatternSMRainbowTunnel.h
- include/screen.h
- platformio.ini
- src/effects.cpp
- src/screen.cpp
Uses FrameEventListener to sync the visualizer to the LED effects, improves FPS calcs.
> Sync effect visualizer to effect output, improve FPS calc, use FrameEventListener
